TakipSistemi/Controllers/VeriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TakipSistemi.Models.Siniflar;

namespace TakipSistemi.Controllers
{
    public class VeriController : Controller
    {
        // GET: VeriEkle
        Context db = new Context();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult VeriEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult VeriEkle(Takip takip)
        {
            int takipToplam = db.Takipler.Count();
            db.Takipler.Add(takip);
            takip.DosyaNo = "2022-000" + takipToplam;
            takip.Tarih = DateTime.Now;
            //takip.Yetkili = ;
            //foreach (var item in db.Kullanicilar)
            //{
            //    if ()
            //    {

            //    }
            //}
            takip.Durum = true;
            db.SaveChanges();
            return RedirectToAction("Index", "TakipListesi");
        }

    }
}

TakipSistemi/Controllers/YoneticiPanelController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TakipSistemi.Models.Siniflar;

namespace TakipSistemi.Controllers
{
    [Authorize(Roles = "Admin")]
    public class YoneticiPanelController : Controller
    {
        Context c = new Context();
        int idKul;
        // GET: YoneticiPanel

        public ActionResult Index()
        {
            var mail = (string)Session["KullaniciMail"];
            
            foreach (var item in c.Kullanicilar)
            {
                if (item.KullaniciMail == mail)
                {
                    idKul = item.KullaniciID;
                }
            }

            var degerler = c.Kullanicilar.Find(idKul);
            ViewBag.m = mail;
            return View(degerler);
        }
        public ActionResult YoneticiGetir(int id)
        {
            var prs = c.Kullanicilar.Find(id);
            return View("KullaniciGetir", prs);
        }

        [HttpPost]
        public ActionResult YoneticiGuncelle(Kullanici kullanici)
        {
            if (ModelState.IsValid)
            {
                c.Entry(kullanici).State = EntityState.Modified;
                kullanici.Durum = true;
                c.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kullanici);
        }

    }
}

TakipSistemi/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html>

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>SAT</title>

    <!-- slider stylesheet -->
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="~/heustonn-html/css/bootstrap.css" />

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700|Roboto:400,700&display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/heustonn-html/css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/heustonn-html/css/responsive.css" rel="stylesheet" />
</head>

<body>

    <div class="hero_area">

        <!-- header section strats -->
        <header class="header_section">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg custom_nav-container ">

                    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                            aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">

                            <ul class="navbar-nav  ">

                                <li class="nav-item @ViewBag.TakipListesi">
                                    <a class="nav-link" href="/TakipListesi/Index">Satın Alma Takip Listesi</a>
                                </li>
                                <li class="nav-item @ViewBag.VeriEkle">
                                    <a class="nav-link" href="@Url.Action("VeriEkle","Veri")">Satın Alma Takip Verisi Ekle</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/Bilgilerim/Index">Bilgilerim</a>
                                </li>
                                <li class="nav-item @ViewBag.VeriEkle">
                                    <a class="nav-link" href="@Url.Action("Index","YoneticiPanel")">Yönetici Paneli</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="~/login/Index">Çıkış Yap</a>
                                </li>

                            </ul>
                        </div>
                    </div>
                    <form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
                        <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
                    </form>
                </nav>
            </div>
        </header>
        <!-- end header section -->
    </div>
    <div class="bg">
        <!-- contact section -->
        @RenderBody()


        <!-- footer section -->
        <section class="container-fluid footer_section">
            <p>
                Copyright &copy; Tüm haklar bize aittir. Feyza Uğuz & Gamze Akçay
                <a href="https://html.design/"></a>
            </p>
        </section>
        <!-- footer section -->

        <script type="text/javascript" src="~/heustonn-html/js/jquery-3.4.1.min.js"></script>
        <script type="text/javascript" src="~/heustonn-html/js/bootstrap.js"></script>
</body>

</html>

TakipSistemi/Views/Shared/YoneticiLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Yetkili Paneli</title>

  <!-- Bootstrap core CSS -->
  <link href="~/webpanelticari/webpanel/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="~/webpanelticari/webpanel/css/simple-sidebar.css" rel="stylesheet">

</head>

<body>

  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading">Yetkili Paneli </div>
      <div class="list-group list-group-flush">
        <a href="/Kullanicilar/Index" class="list-group-item list-group-item-action bg-light">Kullanıcılar</a>
        <a href="@Url.Action("Index","YoneticiPanel")" class="list-group-item list-group-item-action bg-light">Bilgilerim</a>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <button class="btn btn-info" id="menu-toggle">Paneli Gizle</button>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="/TakipListesi/Index/">Ana Sayfa <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="~/login/Index">Çıkış Yap</a>
            </li>
            @*<li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>*@
          </ul>
        </div>
      </nav>

      <div class="container-fluid">
          @RenderBody()
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->
  <script src="~/webpanelticari/webpanel/vendor/jquery/jquery.min.js"></script>
  <script src="~/webpanelticari/webpanel/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>

TakipSistemi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TakipSistemi/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Giriş</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/login-form-v18/Login_v18/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/login-form-v18/Login_v18/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/login-form-v18/Login_v18/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/login-form-v18/Login_v18/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/login-form-v18/Login_v18/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/login-form-v18/Login_v18/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/login-form-v18/Login_v18/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link href="~/login-form-v18/Login_v18/vendor/select2/select2.min.css" rel="stylesheet" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/login-form-v18/Login_v18/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/login-form-v18/Login_v18/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/login-form-v18/Login_v18/css/main.css">
    <!--===============================================================================================-->
</head>


@RenderBody()

<!--===============================================================================================-->

<script src="~/login-form-v18/Login_v18/vendor/jquery/jquery-3.2.1.min.js"></script>
<script src="~/login-form-v18/Login_v18/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->

<script src="~/login-form-v18/Login_v18/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<script src="~/login-form-v18/Login_v18/vendor/bootstrap/js/popper.js"></script>

<script src="~/login-form-v18/Login_v18/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->

<script src="~/login-form-v18/Login_v18/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->

<script src="~/login-form-v18/Login_v18/vendor/daterangepicker/moment.min.js"></script>

<script src="~/login-form-v18/Login_v18/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="~/login-form-v18/Login_v18/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="~/login-form-v18/Login_v18/js/main.js"></script>
</html>